export default function  getData(){
    const fooddata = [
        {
            id: 1,
            name:"可爱多",
            img:"/src/assets/picture/可爱多.jpg",
            category:"冰淇淋",
            kinds:[
               
            ],
        },
        {
            id: 2,
            name:"溜溜梅",
            img:"/src/assets/picture/溜溜梅.jpg",
            category:"零食",
            kinds:[
              {
                id: 1,
                name:"九制梅",
                image:'/src/assets/溜溜梅/九制梅.jpg',
                price:3,
                count: 0,
              },
              {
                id: 2,
                name:"清梅",
                image:'/src/assets/溜溜梅/清梅.jpg',
                price:3,
                count: 0,
              },
              {
                id: 3,
                name:"乌梅",
                image:'/src/assets/溜溜梅/乌梅.jpg',
                price:3,
                count: 0,
              },
              {
                id: 4,
                name:"雪梅",
                image:'/src/assets/溜溜梅/雪梅.jpg',
                price:3,
                count: 0,
              },
              {
                id: 5,
                name:"咖啡梅",
                image:'/src/assets/溜溜梅/咖啡梅.jpg',
                price:3,
                count: 0,
              },
              {
                id: 6,
                name:"话梅",
                image:'/src/assets/溜溜梅/话梅.jpg',
                price:3,
                count: 0,
              },
              {
                id: 7,
                name:"情人梅",
                image:'/src/assets/溜溜梅/情人梅.jpg',
                price:3,
                count: 0,
              },
              {
                id: 8,
                name:"凤梨梅",
                image:'/src/assets/溜溜梅/凤梨梅.jpg',
                price:3,
                count: 0,
              },
              {
                id: 9,
                name:"绿茶梅",
                image:'/src/assets/溜溜梅/绿茶梅.jpg',
                price:3,
                count: 0,
              }
            ],
        },
        {
            id: 3,
            name:"奥利奥",
            img:"/src/assets/picture/奥利奥.jpg",
            category:"零食",
            kinds:[
                {
                  id: 1,
                  name:"九制梅",
                  image:'/src/assets/溜溜梅/九制梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 2,
                  name:"清梅",
                  image:'/src/assets/溜溜梅/清梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 3,
                  name:"乌梅",
                  image:'/src/assets/溜溜梅/乌梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 4,
                  name:"雪梅",
                  image:'/src/assets/溜溜梅/雪梅.jpg',
                  price:3,
                  count: 0,
                },
              ],
        },
        {
            id: 4,
            name:"麻辣王子",
            img:"/src/assets/picture/麻辣王子.jpg",
            category:"辣条",
            kinds:[
                {
                  id: 1,
                  name:"九制梅",
                  image:'/src/assets/溜溜梅/九制梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 2,
                  name:"清梅",
                  image:'/src/assets/溜溜梅/清梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 3,
                  name:"乌梅",
                  image:'/src/assets/溜溜梅/乌梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 4,
                  name:"雪梅",
                  image:'/src/assets/溜溜梅/雪梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 5,
                  name:"咖啡梅",
                  image:'/src/assets/溜溜梅/咖啡梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 6,
                  name:"话梅",
                  image:'/src/assets/溜溜梅/话梅.jpg',
                  price:3,
                  count: 0,
                },
              ],
        },
        {
            id: 5,
            name:"麻辣王子",
            img:"/src/assets/picture/麻辣王子.jpg",
            category:"辣条",
            kinds:[
                {
                  id: 1,
                  name:"九制梅",
                  image:'/src/assets/溜溜梅/九制梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 2,
                  name:"清梅",
                  image:'/src/assets/溜溜梅/清梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 3,
                  name:"乌梅",
                  image:'/src/assets/溜溜梅/乌梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 4,
                  name:"雪梅",
                  image:'/src/assets/溜溜梅/雪梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 5,
                  name:"咖啡梅",
                  image:'/src/assets/溜溜梅/咖啡梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 6,
                  name:"话梅",
                  image:'/src/assets/溜溜梅/话梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 7,
                  name:"情人梅",
                  image:'/src/assets/溜溜梅/情人梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 8,
                  name:"凤梨梅",
                  image:'/src/assets/溜溜梅/凤梨梅.jpg',
                  price:3,
                  count: 0,
                },
                {
                  id: 9,
                  name:"绿茶梅",
                  image:'/src/assets/溜溜梅/绿茶梅.jpg',
                  price:3,
                  count: 0,
                }
              ],
        },
        {
            id: 6,
            name:"麻辣王子",
            img:"/src/assets/picture/麻辣王子.jpg",
            category:"辣条",
            count: 0,
        },
        {
            id: 7,
            name:"麻辣王子",
            img:"/src/assets/picture/麻辣王子.jpg",
            category:"辣条",
            count: 0,
        },
        {
            id: 8,
            name:"麻辣王子",
            img:"/src/assets/picture/麻辣王子.jpg",
            category:"辣条",
            count: 0,
        },
        {
            id: 9,
            name:"麻辣王子",
            img:"/src/assets/picture/麻辣王子.jpg",
            category:"辣条",
            count: 0,
        },
        {
            id: 10,
            name:"麻辣王子",
            img:"/src/assets/picture/麻辣王子.jpg",
            category:"辣条",
            count: 0,
        },
    ]
    return fooddata
}
